external-dns:
  podAnnotations: 
    "iam.amazonaws.com/role" : "kiam-full-access"
  enabled: {{ .Requirements.ingress.externalDNS }}
  sources:
  - ingress
  provider: aws
  # google:
  #   serviceAccountSecret: external-dns-gcp-sa
  rbac:
    create: true
  domainFilters:
  - "{{ .Requirements.ingress.domain }}"
